# Generated by Django 4.1.2 on 2023-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playuser",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="playuser",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
