# Generated by Django 4.1.6 on 2023-03-04 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="homeroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homeroom_id",
                    models.IntegerField(
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^\\d{8}$")],
                    ),
                ),
                ("teacher_id", models.CharField(max_length=150)),
            ],
        ),
    ]
